# Generated by Django 5.2.4 on 2025-07-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='Untiltled', max_length=255),
        ),
    ]
